spring:
    application:
       name: fastdelivery
    profiles:
       active: local,default
    datasource:
       url: jdbc:postgresql://localhost:5432/postgres
       username: postgres
       password: root
       driver-class-name: org.postgresql.Driver
       schema: delivery